version: "3.2"
services:
  app:
    build: ./app
    links: 
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/app/
    container_name: container_app_flask

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1927ad19
      MYSQL_USER: flask_mysql_user
      MYSQL_PASSWORD: flask_mysql_pass
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    container_name: container_mysql